using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraFollow : MonoBehaviour
{

    [SerializeField] private Vector3 offset = new Vector3(0f, 3f, -6f);
    [SerializeField] private Transform target; //the target vehicle to follow
    [SerializeField] private float translateSpeed = 10;
    [SerializeField] private float rotationSpeed = 10;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    private void FixedUpdate()
    {

        HandleTranslation();
        HandleRotation();
    }

    /// <summary>
    /// handling the rotation of the camera
    /// </summary>
    private void HandleRotation()
    {
        var targetPosition = target.TransformPoint(offset);
        transform.position = Vector3
        .Lerp(transform.position
        , targetPosition, translateSpeed * Time.deltaTime);
    }

    /// <summary>
    /// handling the translation of the camera
    /// </summary>
    private void HandleTranslation()
    {
        var direction =
        target.position - transform.position;
        var rotation = Quaternion
            .LookRotation(direction, Vector3.up);
        transform.rotation =
        Quaternion.Lerp(transform.rotation, rotation
        , rotationSpeed * Time.deltaTime);
    }

}
